// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloudprovider/externalgrpc/protos/externalgrpc.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	v11 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InstanceStatus_InstanceState int32

const (
	// an Unspecified instanceState means the actual instance status is undefined (nil).
	InstanceStatus_unspecified InstanceStatus_InstanceState = 0
	// InstanceRunning means instance is running.
	InstanceStatus_instanceRunning InstanceStatus_InstanceState = 1
	// InstanceCreating means instance is being created.
	InstanceStatus_instanceCreating InstanceStatus_InstanceState = 2
	// InstanceDeleting means instance is being deleted.
	InstanceStatus_instanceDeleting InstanceStatus_InstanceState = 3
)

var InstanceStatus_InstanceState_name = map[int32]string{
	0: "unspecified",
	1: "instanceRunning",
	2: "instanceCreating",
	3: "instanceDeleting",
}

var InstanceStatus_InstanceState_value = map[string]int32{
	"unspecified":      0,
	"instanceRunning":  1,
	"instanceCreating": 2,
	"instanceDeleting": 3,
}

func (x InstanceStatus_InstanceState) String() string {
	return proto.EnumName(InstanceStatus_InstanceState_name, int32(x))
}

func (InstanceStatus_InstanceState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{29, 0}
}

type NodeGroup struct {
	// ID of the node group on the cloud provider.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// MinSize of the node group on the cloud provider.
	MinSize int32 `protobuf:"varint,2,opt,name=minSize,proto3" json:"minSize,omitempty"`
	// MaxSize of the node group on the cloud provider.
	MaxSize int32 `protobuf:"varint,3,opt,name=maxSize,proto3" json:"maxSize,omitempty"`
	// Debug returns a string containing all information regarding this node group.
	Debug                string   `protobuf:"bytes,4,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroup) Reset()         { *m = NodeGroup{} }
func (m *NodeGroup) String() string { return proto.CompactTextString(m) }
func (*NodeGroup) ProtoMessage()    {}
func (*NodeGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{0}
}

func (m *NodeGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroup.Unmarshal(m, b)
}
func (m *NodeGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroup.Marshal(b, m, deterministic)
}
func (m *NodeGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroup.Merge(m, src)
}
func (m *NodeGroup) XXX_Size() int {
	return xxx_messageInfo_NodeGroup.Size(m)
}
func (m *NodeGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroup.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroup proto.InternalMessageInfo

func (m *NodeGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeGroup) GetMinSize() int32 {
	if m != nil {
		return m.MinSize
	}
	return 0
}

func (m *NodeGroup) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *NodeGroup) GetDebug() string {
	if m != nil {
		return m.Debug
	}
	return ""
}

type ExternalGrpcNode struct {
	// ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID>.
	ProviderID string `protobuf:"bytes,1,opt,name=providerID,proto3" json:"providerID,omitempty"`
	// Name of the node assigned by the cloud provider.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// labels is a map of {key,value} pairs with the node's labels.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// If specified, the node's annotations.
	Annotations          map[string]string `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExternalGrpcNode) Reset()         { *m = ExternalGrpcNode{} }
func (m *ExternalGrpcNode) String() string { return proto.CompactTextString(m) }
func (*ExternalGrpcNode) ProtoMessage()    {}
func (*ExternalGrpcNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{1}
}

func (m *ExternalGrpcNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalGrpcNode.Unmarshal(m, b)
}
func (m *ExternalGrpcNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalGrpcNode.Marshal(b, m, deterministic)
}
func (m *ExternalGrpcNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalGrpcNode.Merge(m, src)
}
func (m *ExternalGrpcNode) XXX_Size() int {
	return xxx_messageInfo_ExternalGrpcNode.Size(m)
}
func (m *ExternalGrpcNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalGrpcNode.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalGrpcNode proto.InternalMessageInfo

func (m *ExternalGrpcNode) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *ExternalGrpcNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExternalGrpcNode) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ExternalGrpcNode) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

type NodeGroupsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupsRequest) Reset()         { *m = NodeGroupsRequest{} }
func (m *NodeGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGroupsRequest) ProtoMessage()    {}
func (*NodeGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{2}
}

func (m *NodeGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupsRequest.Unmarshal(m, b)
}
func (m *NodeGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupsRequest.Marshal(b, m, deterministic)
}
func (m *NodeGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupsRequest.Merge(m, src)
}
func (m *NodeGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGroupsRequest.Size(m)
}
func (m *NodeGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupsRequest proto.InternalMessageInfo

type NodeGroupsResponse struct {
	// All the node groups that the cloud provider service supports.
	NodeGroups           []*NodeGroup `protobuf:"bytes,1,rep,name=nodeGroups,proto3" json:"nodeGroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NodeGroupsResponse) Reset()         { *m = NodeGroupsResponse{} }
func (m *NodeGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGroupsResponse) ProtoMessage()    {}
func (*NodeGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{3}
}

func (m *NodeGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupsResponse.Unmarshal(m, b)
}
func (m *NodeGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupsResponse.Marshal(b, m, deterministic)
}
func (m *NodeGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupsResponse.Merge(m, src)
}
func (m *NodeGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGroupsResponse.Size(m)
}
func (m *NodeGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupsResponse proto.InternalMessageInfo

func (m *NodeGroupsResponse) GetNodeGroups() []*NodeGroup {
	if m != nil {
		return m.NodeGroups
	}
	return nil
}

type NodeGroupForNodeRequest struct {
	// Node for which the request is performed.
	Node                 *ExternalGrpcNode `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeGroupForNodeRequest) Reset()         { *m = NodeGroupForNodeRequest{} }
func (m *NodeGroupForNodeRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGroupForNodeRequest) ProtoMessage()    {}
func (*NodeGroupForNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{4}
}

func (m *NodeGroupForNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupForNodeRequest.Unmarshal(m, b)
}
func (m *NodeGroupForNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupForNodeRequest.Marshal(b, m, deterministic)
}
func (m *NodeGroupForNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupForNodeRequest.Merge(m, src)
}
func (m *NodeGroupForNodeRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGroupForNodeRequest.Size(m)
}
func (m *NodeGroupForNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupForNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupForNodeRequest proto.InternalMessageInfo

func (m *NodeGroupForNodeRequest) GetNode() *ExternalGrpcNode {
	if m != nil {
		return m.Node
	}
	return nil
}

type NodeGroupForNodeResponse struct {
	// Node group for the given node. nodeGroup with id = "" means no node group.
	NodeGroup            *NodeGroup `protobuf:"bytes,1,opt,name=nodeGroup,proto3" json:"nodeGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NodeGroupForNodeResponse) Reset()         { *m = NodeGroupForNodeResponse{} }
func (m *NodeGroupForNodeResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGroupForNodeResponse) ProtoMessage()    {}
func (*NodeGroupForNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{5}
}

func (m *NodeGroupForNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupForNodeResponse.Unmarshal(m, b)
}
func (m *NodeGroupForNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupForNodeResponse.Marshal(b, m, deterministic)
}
func (m *NodeGroupForNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupForNodeResponse.Merge(m, src)
}
func (m *NodeGroupForNodeResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGroupForNodeResponse.Size(m)
}
func (m *NodeGroupForNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupForNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupForNodeResponse proto.InternalMessageInfo

func (m *NodeGroupForNodeResponse) GetNodeGroup() *NodeGroup {
	if m != nil {
		return m.NodeGroup
	}
	return nil
}

type PricingNodePriceRequest struct {
	// Node for which the request is performed.
	Node *ExternalGrpcNode `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// Start time for the request period.
	StartTime *v1.Time `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// End time for the request period.
	EndTime              *v1.Time `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PricingNodePriceRequest) Reset()         { *m = PricingNodePriceRequest{} }
func (m *PricingNodePriceRequest) String() string { return proto.CompactTextString(m) }
func (*PricingNodePriceRequest) ProtoMessage()    {}
func (*PricingNodePriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{6}
}

func (m *PricingNodePriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricingNodePriceRequest.Unmarshal(m, b)
}
func (m *PricingNodePriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricingNodePriceRequest.Marshal(b, m, deterministic)
}
func (m *PricingNodePriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricingNodePriceRequest.Merge(m, src)
}
func (m *PricingNodePriceRequest) XXX_Size() int {
	return xxx_messageInfo_PricingNodePriceRequest.Size(m)
}
func (m *PricingNodePriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PricingNodePriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PricingNodePriceRequest proto.InternalMessageInfo

func (m *PricingNodePriceRequest) GetNode() *ExternalGrpcNode {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *PricingNodePriceRequest) GetStartTime() *v1.Time {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *PricingNodePriceRequest) GetEndTime() *v1.Time {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type PricingNodePriceResponse struct {
	// Theoretical minimum price of running a node for a given period.
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PricingNodePriceResponse) Reset()         { *m = PricingNodePriceResponse{} }
func (m *PricingNodePriceResponse) String() string { return proto.CompactTextString(m) }
func (*PricingNodePriceResponse) ProtoMessage()    {}
func (*PricingNodePriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{7}
}

func (m *PricingNodePriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricingNodePriceResponse.Unmarshal(m, b)
}
func (m *PricingNodePriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricingNodePriceResponse.Marshal(b, m, deterministic)
}
func (m *PricingNodePriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricingNodePriceResponse.Merge(m, src)
}
func (m *PricingNodePriceResponse) XXX_Size() int {
	return xxx_messageInfo_PricingNodePriceResponse.Size(m)
}
func (m *PricingNodePriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PricingNodePriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PricingNodePriceResponse proto.InternalMessageInfo

func (m *PricingNodePriceResponse) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type PricingPodPriceRequest struct {
	// Pod for which the request is performed.
	Pod *v11.Pod `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	// Start time for the request period.
	StartTime *v1.Time `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// End time for the request period.
	EndTime              *v1.Time `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PricingPodPriceRequest) Reset()         { *m = PricingPodPriceRequest{} }
func (m *PricingPodPriceRequest) String() string { return proto.CompactTextString(m) }
func (*PricingPodPriceRequest) ProtoMessage()    {}
func (*PricingPodPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{8}
}

func (m *PricingPodPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricingPodPriceRequest.Unmarshal(m, b)
}
func (m *PricingPodPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricingPodPriceRequest.Marshal(b, m, deterministic)
}
func (m *PricingPodPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricingPodPriceRequest.Merge(m, src)
}
func (m *PricingPodPriceRequest) XXX_Size() int {
	return xxx_messageInfo_PricingPodPriceRequest.Size(m)
}
func (m *PricingPodPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PricingPodPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PricingPodPriceRequest proto.InternalMessageInfo

func (m *PricingPodPriceRequest) GetPod() *v11.Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *PricingPodPriceRequest) GetStartTime() *v1.Time {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *PricingPodPriceRequest) GetEndTime() *v1.Time {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type PricingPodPriceResponse struct {
	// Theoretical minimum price of running a pod for a given period.
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PricingPodPriceResponse) Reset()         { *m = PricingPodPriceResponse{} }
func (m *PricingPodPriceResponse) String() string { return proto.CompactTextString(m) }
func (*PricingPodPriceResponse) ProtoMessage()    {}
func (*PricingPodPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{9}
}

func (m *PricingPodPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricingPodPriceResponse.Unmarshal(m, b)
}
func (m *PricingPodPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricingPodPriceResponse.Marshal(b, m, deterministic)
}
func (m *PricingPodPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricingPodPriceResponse.Merge(m, src)
}
func (m *PricingPodPriceResponse) XXX_Size() int {
	return xxx_messageInfo_PricingPodPriceResponse.Size(m)
}
func (m *PricingPodPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PricingPodPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PricingPodPriceResponse proto.InternalMessageInfo

func (m *PricingPodPriceResponse) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GPULabelRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPULabelRequest) Reset()         { *m = GPULabelRequest{} }
func (m *GPULabelRequest) String() string { return proto.CompactTextString(m) }
func (*GPULabelRequest) ProtoMessage()    {}
func (*GPULabelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{10}
}

func (m *GPULabelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPULabelRequest.Unmarshal(m, b)
}
func (m *GPULabelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPULabelRequest.Marshal(b, m, deterministic)
}
func (m *GPULabelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPULabelRequest.Merge(m, src)
}
func (m *GPULabelRequest) XXX_Size() int {
	return xxx_messageInfo_GPULabelRequest.Size(m)
}
func (m *GPULabelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GPULabelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GPULabelRequest proto.InternalMessageInfo

type GPULabelResponse struct {
	// Label added to nodes with a GPU resource.
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPULabelResponse) Reset()         { *m = GPULabelResponse{} }
func (m *GPULabelResponse) String() string { return proto.CompactTextString(m) }
func (*GPULabelResponse) ProtoMessage()    {}
func (*GPULabelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{11}
}

func (m *GPULabelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPULabelResponse.Unmarshal(m, b)
}
func (m *GPULabelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPULabelResponse.Marshal(b, m, deterministic)
}
func (m *GPULabelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPULabelResponse.Merge(m, src)
}
func (m *GPULabelResponse) XXX_Size() int {
	return xxx_messageInfo_GPULabelResponse.Size(m)
}
func (m *GPULabelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GPULabelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GPULabelResponse proto.InternalMessageInfo

func (m *GPULabelResponse) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type GetAvailableGPUTypesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAvailableGPUTypesRequest) Reset()         { *m = GetAvailableGPUTypesRequest{} }
func (m *GetAvailableGPUTypesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAvailableGPUTypesRequest) ProtoMessage()    {}
func (*GetAvailableGPUTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{12}
}

func (m *GetAvailableGPUTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAvailableGPUTypesRequest.Unmarshal(m, b)
}
func (m *GetAvailableGPUTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAvailableGPUTypesRequest.Marshal(b, m, deterministic)
}
func (m *GetAvailableGPUTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvailableGPUTypesRequest.Merge(m, src)
}
func (m *GetAvailableGPUTypesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAvailableGPUTypesRequest.Size(m)
}
func (m *GetAvailableGPUTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvailableGPUTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvailableGPUTypesRequest proto.InternalMessageInfo

type GetAvailableGPUTypesResponse struct {
	// GPU types passed in as opaque key-value pairs.
	GpuTypes             map[string]*any.Any `protobuf:"bytes,1,rep,name=gpuTypes,proto3" json:"gpuTypes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAvailableGPUTypesResponse) Reset()         { *m = GetAvailableGPUTypesResponse{} }
func (m *GetAvailableGPUTypesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAvailableGPUTypesResponse) ProtoMessage()    {}
func (*GetAvailableGPUTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{13}
}

func (m *GetAvailableGPUTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAvailableGPUTypesResponse.Unmarshal(m, b)
}
func (m *GetAvailableGPUTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAvailableGPUTypesResponse.Marshal(b, m, deterministic)
}
func (m *GetAvailableGPUTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAvailableGPUTypesResponse.Merge(m, src)
}
func (m *GetAvailableGPUTypesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAvailableGPUTypesResponse.Size(m)
}
func (m *GetAvailableGPUTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAvailableGPUTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAvailableGPUTypesResponse proto.InternalMessageInfo

func (m *GetAvailableGPUTypesResponse) GetGpuTypes() map[string]*any.Any {
	if m != nil {
		return m.GpuTypes
	}
	return nil
}

type CleanupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanupRequest) Reset()         { *m = CleanupRequest{} }
func (m *CleanupRequest) String() string { return proto.CompactTextString(m) }
func (*CleanupRequest) ProtoMessage()    {}
func (*CleanupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{14}
}

func (m *CleanupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanupRequest.Unmarshal(m, b)
}
func (m *CleanupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanupRequest.Marshal(b, m, deterministic)
}
func (m *CleanupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanupRequest.Merge(m, src)
}
func (m *CleanupRequest) XXX_Size() int {
	return xxx_messageInfo_CleanupRequest.Size(m)
}
func (m *CleanupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CleanupRequest proto.InternalMessageInfo

type CleanupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanupResponse) Reset()         { *m = CleanupResponse{} }
func (m *CleanupResponse) String() string { return proto.CompactTextString(m) }
func (*CleanupResponse) ProtoMessage()    {}
func (*CleanupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{15}
}

func (m *CleanupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanupResponse.Unmarshal(m, b)
}
func (m *CleanupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanupResponse.Marshal(b, m, deterministic)
}
func (m *CleanupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanupResponse.Merge(m, src)
}
func (m *CleanupResponse) XXX_Size() int {
	return xxx_messageInfo_CleanupResponse.Size(m)
}
func (m *CleanupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CleanupResponse proto.InternalMessageInfo

type RefreshRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{16}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

type RefreshResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshResponse) Reset()         { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()    {}
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{17}
}

func (m *RefreshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshResponse.Unmarshal(m, b)
}
func (m *RefreshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshResponse.Marshal(b, m, deterministic)
}
func (m *RefreshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshResponse.Merge(m, src)
}
func (m *RefreshResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshResponse.Size(m)
}
func (m *RefreshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshResponse proto.InternalMessageInfo

type NodeGroupTargetSizeRequest struct {
	// ID of the node group for the request.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupTargetSizeRequest) Reset()         { *m = NodeGroupTargetSizeRequest{} }
func (m *NodeGroupTargetSizeRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGroupTargetSizeRequest) ProtoMessage()    {}
func (*NodeGroupTargetSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{18}
}

func (m *NodeGroupTargetSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupTargetSizeRequest.Unmarshal(m, b)
}
func (m *NodeGroupTargetSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupTargetSizeRequest.Marshal(b, m, deterministic)
}
func (m *NodeGroupTargetSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupTargetSizeRequest.Merge(m, src)
}
func (m *NodeGroupTargetSizeRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGroupTargetSizeRequest.Size(m)
}
func (m *NodeGroupTargetSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupTargetSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupTargetSizeRequest proto.InternalMessageInfo

func (m *NodeGroupTargetSizeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NodeGroupTargetSizeResponse struct {
	// Current target size of the node group.
	TargetSize           int32    `protobuf:"varint,1,opt,name=targetSize,proto3" json:"targetSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupTargetSizeResponse) Reset()         { *m = NodeGroupTargetSizeResponse{} }
func (m *NodeGroupTargetSizeResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGroupTargetSizeResponse) ProtoMessage()    {}
func (*NodeGroupTargetSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{19}
}

func (m *NodeGroupTargetSizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupTargetSizeResponse.Unmarshal(m, b)
}
func (m *NodeGroupTargetSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupTargetSizeResponse.Marshal(b, m, deterministic)
}
func (m *NodeGroupTargetSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupTargetSizeResponse.Merge(m, src)
}
func (m *NodeGroupTargetSizeResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGroupTargetSizeResponse.Size(m)
}
func (m *NodeGroupTargetSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupTargetSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupTargetSizeResponse proto.InternalMessageInfo

func (m *NodeGroupTargetSizeResponse) GetTargetSize() int32 {
	if m != nil {
		return m.TargetSize
	}
	return 0
}

type NodeGroupIncreaseSizeRequest struct {
	// Number of nodes to add.
	Delta int32 `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	// ID of the node group for the request.
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupIncreaseSizeRequest) Reset()         { *m = NodeGroupIncreaseSizeRequest{} }
func (m *NodeGroupIncreaseSizeRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGroupIncreaseSizeRequest) ProtoMessage()    {}
func (*NodeGroupIncreaseSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{20}
}

func (m *NodeGroupIncreaseSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupIncreaseSizeRequest.Unmarshal(m, b)
}
func (m *NodeGroupIncreaseSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupIncreaseSizeRequest.Marshal(b, m, deterministic)
}
func (m *NodeGroupIncreaseSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupIncreaseSizeRequest.Merge(m, src)
}
func (m *NodeGroupIncreaseSizeRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGroupIncreaseSizeRequest.Size(m)
}
func (m *NodeGroupIncreaseSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupIncreaseSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupIncreaseSizeRequest proto.InternalMessageInfo

func (m *NodeGroupIncreaseSizeRequest) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func (m *NodeGroupIncreaseSizeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NodeGroupIncreaseSizeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupIncreaseSizeResponse) Reset()         { *m = NodeGroupIncreaseSizeResponse{} }
func (m *NodeGroupIncreaseSizeResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGroupIncreaseSizeResponse) ProtoMessage()    {}
func (*NodeGroupIncreaseSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{21}
}

func (m *NodeGroupIncreaseSizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupIncreaseSizeResponse.Unmarshal(m, b)
}
func (m *NodeGroupIncreaseSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupIncreaseSizeResponse.Marshal(b, m, deterministic)
}
func (m *NodeGroupIncreaseSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupIncreaseSizeResponse.Merge(m, src)
}
func (m *NodeGroupIncreaseSizeResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGroupIncreaseSizeResponse.Size(m)
}
func (m *NodeGroupIncreaseSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupIncreaseSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupIncreaseSizeResponse proto.InternalMessageInfo

type NodeGroupDeleteNodesRequest struct {
	// List of nodes to delete.
	Nodes []*ExternalGrpcNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// ID of the node group for the request.
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupDeleteNodesRequest) Reset()         { *m = NodeGroupDeleteNodesRequest{} }
func (m *NodeGroupDeleteNodesRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGroupDeleteNodesRequest) ProtoMessage()    {}
func (*NodeGroupDeleteNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{22}
}

func (m *NodeGroupDeleteNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupDeleteNodesRequest.Unmarshal(m, b)
}
func (m *NodeGroupDeleteNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupDeleteNodesRequest.Marshal(b, m, deterministic)
}
func (m *NodeGroupDeleteNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupDeleteNodesRequest.Merge(m, src)
}
func (m *NodeGroupDeleteNodesRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGroupDeleteNodesRequest.Size(m)
}
func (m *NodeGroupDeleteNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupDeleteNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupDeleteNodesRequest proto.InternalMessageInfo

func (m *NodeGroupDeleteNodesRequest) GetNodes() []*ExternalGrpcNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *NodeGroupDeleteNodesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NodeGroupDeleteNodesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupDeleteNodesResponse) Reset()         { *m = NodeGroupDeleteNodesResponse{} }
func (m *NodeGroupDeleteNodesResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGroupDeleteNodesResponse) ProtoMessage()    {}
func (*NodeGroupDeleteNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{23}
}

func (m *NodeGroupDeleteNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupDeleteNodesResponse.Unmarshal(m, b)
}
func (m *NodeGroupDeleteNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupDeleteNodesResponse.Marshal(b, m, deterministic)
}
func (m *NodeGroupDeleteNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupDeleteNodesResponse.Merge(m, src)
}
func (m *NodeGroupDeleteNodesResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGroupDeleteNodesResponse.Size(m)
}
func (m *NodeGroupDeleteNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupDeleteNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupDeleteNodesResponse proto.InternalMessageInfo

type NodeGroupDecreaseTargetSizeRequest struct {
	// Number of nodes to delete.
	Delta int32 `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	// ID of the node group for the request.
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupDecreaseTargetSizeRequest) Reset()         { *m = NodeGroupDecreaseTargetSizeRequest{} }
func (m *NodeGroupDecreaseTargetSizeRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGroupDecreaseTargetSizeRequest) ProtoMessage()    {}
func (*NodeGroupDecreaseTargetSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{24}
}

func (m *NodeGroupDecreaseTargetSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupDecreaseTargetSizeRequest.Unmarshal(m, b)
}
func (m *NodeGroupDecreaseTargetSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupDecreaseTargetSizeRequest.Marshal(b, m, deterministic)
}
func (m *NodeGroupDecreaseTargetSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupDecreaseTargetSizeRequest.Merge(m, src)
}
func (m *NodeGroupDecreaseTargetSizeRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGroupDecreaseTargetSizeRequest.Size(m)
}
func (m *NodeGroupDecreaseTargetSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupDecreaseTargetSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupDecreaseTargetSizeRequest proto.InternalMessageInfo

func (m *NodeGroupDecreaseTargetSizeRequest) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func (m *NodeGroupDecreaseTargetSizeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NodeGroupDecreaseTargetSizeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupDecreaseTargetSizeResponse) Reset()         { *m = NodeGroupDecreaseTargetSizeResponse{} }
func (m *NodeGroupDecreaseTargetSizeResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGroupDecreaseTargetSizeResponse) ProtoMessage()    {}
func (*NodeGroupDecreaseTargetSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{25}
}

func (m *NodeGroupDecreaseTargetSizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupDecreaseTargetSizeResponse.Unmarshal(m, b)
}
func (m *NodeGroupDecreaseTargetSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupDecreaseTargetSizeResponse.Marshal(b, m, deterministic)
}
func (m *NodeGroupDecreaseTargetSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupDecreaseTargetSizeResponse.Merge(m, src)
}
func (m *NodeGroupDecreaseTargetSizeResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGroupDecreaseTargetSizeResponse.Size(m)
}
func (m *NodeGroupDecreaseTargetSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupDecreaseTargetSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupDecreaseTargetSizeResponse proto.InternalMessageInfo

type NodeGroupNodesRequest struct {
	// ID of the node group for the request.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupNodesRequest) Reset()         { *m = NodeGroupNodesRequest{} }
func (m *NodeGroupNodesRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGroupNodesRequest) ProtoMessage()    {}
func (*NodeGroupNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{26}
}

func (m *NodeGroupNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupNodesRequest.Unmarshal(m, b)
}
func (m *NodeGroupNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupNodesRequest.Marshal(b, m, deterministic)
}
func (m *NodeGroupNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupNodesRequest.Merge(m, src)
}
func (m *NodeGroupNodesRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGroupNodesRequest.Size(m)
}
func (m *NodeGroupNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupNodesRequest proto.InternalMessageInfo

func (m *NodeGroupNodesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NodeGroupNodesResponse struct {
	// list of cloud provider instances in a node group.
	Instances            []*Instance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NodeGroupNodesResponse) Reset()         { *m = NodeGroupNodesResponse{} }
func (m *NodeGroupNodesResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGroupNodesResponse) ProtoMessage()    {}
func (*NodeGroupNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{27}
}

func (m *NodeGroupNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupNodesResponse.Unmarshal(m, b)
}
func (m *NodeGroupNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupNodesResponse.Marshal(b, m, deterministic)
}
func (m *NodeGroupNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupNodesResponse.Merge(m, src)
}
func (m *NodeGroupNodesResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGroupNodesResponse.Size(m)
}
func (m *NodeGroupNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupNodesResponse proto.InternalMessageInfo

func (m *NodeGroupNodesResponse) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type Instance struct {
	// Id of the instance.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Status of the node.
	Status               *InstanceStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{28}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Instance) GetStatus() *InstanceStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// InstanceStatus represents the instance status.
type InstanceStatus struct {
	// InstanceState tells if the instance is running, being created or being deleted.
	InstanceState InstanceStatus_InstanceState `protobuf:"varint,1,opt,name=instanceState,proto3,enum=clusterautoscaler.cloudprovider.v1.externalgrpc.InstanceStatus_InstanceState" json:"instanceState,omitempty"`
	// ErrorInfo provides information about the error status.
	// If there is no error condition related to instance, then errorInfo.errorCode should be an empty string.
	ErrorInfo            *InstanceErrorInfo `protobuf:"bytes,2,opt,name=errorInfo,proto3" json:"errorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InstanceStatus) Reset()         { *m = InstanceStatus{} }
func (m *InstanceStatus) String() string { return proto.CompactTextString(m) }
func (*InstanceStatus) ProtoMessage()    {}
func (*InstanceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{29}
}

func (m *InstanceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceStatus.Unmarshal(m, b)
}
func (m *InstanceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceStatus.Marshal(b, m, deterministic)
}
func (m *InstanceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceStatus.Merge(m, src)
}
func (m *InstanceStatus) XXX_Size() int {
	return xxx_messageInfo_InstanceStatus.Size(m)
}
func (m *InstanceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceStatus proto.InternalMessageInfo

func (m *InstanceStatus) GetInstanceState() InstanceStatus_InstanceState {
	if m != nil {
		return m.InstanceState
	}
	return InstanceStatus_unspecified
}

func (m *InstanceStatus) GetErrorInfo() *InstanceErrorInfo {
	if m != nil {
		return m.ErrorInfo
	}
	return nil
}

// InstanceErrorInfo provides information about error condition on instance.
type InstanceErrorInfo struct {
	// ErrorCode is cloud-provider specific error code for error condition.
	// An empty string for errorCode means there is no errorInfo for the instance (nil).
	ErrorCode string `protobuf:"bytes,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// ErrorMessage is the human readable description of error condition.
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	// InstanceErrorClass defines the class of error condition.
	InstanceErrorClass   int32    `protobuf:"varint,3,opt,name=instanceErrorClass,proto3" json:"instanceErrorClass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceErrorInfo) Reset()         { *m = InstanceErrorInfo{} }
func (m *InstanceErrorInfo) String() string { return proto.CompactTextString(m) }
func (*InstanceErrorInfo) ProtoMessage()    {}
func (*InstanceErrorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{30}
}

func (m *InstanceErrorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceErrorInfo.Unmarshal(m, b)
}
func (m *InstanceErrorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceErrorInfo.Marshal(b, m, deterministic)
}
func (m *InstanceErrorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceErrorInfo.Merge(m, src)
}
func (m *InstanceErrorInfo) XXX_Size() int {
	return xxx_messageInfo_InstanceErrorInfo.Size(m)
}
func (m *InstanceErrorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceErrorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceErrorInfo proto.InternalMessageInfo

func (m *InstanceErrorInfo) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *InstanceErrorInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *InstanceErrorInfo) GetInstanceErrorClass() int32 {
	if m != nil {
		return m.InstanceErrorClass
	}
	return 0
}

type NodeGroupTemplateNodeInfoRequest struct {
	// ID of the node group for the request.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeGroupTemplateNodeInfoRequest) Reset()         { *m = NodeGroupTemplateNodeInfoRequest{} }
func (m *NodeGroupTemplateNodeInfoRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGroupTemplateNodeInfoRequest) ProtoMessage()    {}
func (*NodeGroupTemplateNodeInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{31}
}

func (m *NodeGroupTemplateNodeInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupTemplateNodeInfoRequest.Unmarshal(m, b)
}
func (m *NodeGroupTemplateNodeInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupTemplateNodeInfoRequest.Marshal(b, m, deterministic)
}
func (m *NodeGroupTemplateNodeInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupTemplateNodeInfoRequest.Merge(m, src)
}
func (m *NodeGroupTemplateNodeInfoRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGroupTemplateNodeInfoRequest.Size(m)
}
func (m *NodeGroupTemplateNodeInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupTemplateNodeInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupTemplateNodeInfoRequest proto.InternalMessageInfo

func (m *NodeGroupTemplateNodeInfoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NodeGroupTemplateNodeInfoResponse struct {
	// nodeInfo is the extracted data from the cloud provider, as a primitive Kubernetes Node type.
	NodeInfo             *v11.Node `protobuf:"bytes,1,opt,name=nodeInfo,proto3" json:"nodeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NodeGroupTemplateNodeInfoResponse) Reset()         { *m = NodeGroupTemplateNodeInfoResponse{} }
func (m *NodeGroupTemplateNodeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGroupTemplateNodeInfoResponse) ProtoMessage()    {}
func (*NodeGroupTemplateNodeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{32}
}

func (m *NodeGroupTemplateNodeInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupTemplateNodeInfoResponse.Unmarshal(m, b)
}
func (m *NodeGroupTemplateNodeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupTemplateNodeInfoResponse.Marshal(b, m, deterministic)
}
func (m *NodeGroupTemplateNodeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupTemplateNodeInfoResponse.Merge(m, src)
}
func (m *NodeGroupTemplateNodeInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGroupTemplateNodeInfoResponse.Size(m)
}
func (m *NodeGroupTemplateNodeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupTemplateNodeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupTemplateNodeInfoResponse proto.InternalMessageInfo

func (m *NodeGroupTemplateNodeInfoResponse) GetNodeInfo() *v11.Node {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

type NodeGroupAutoscalingOptions struct {
	// ScaleDownUtilizationThreshold sets threshold for nodes to be considered for scale down
	// if cpu or memory utilization is over threshold.
	ScaleDownUtilizationThreshold float64 `protobuf:"fixed64,1,opt,name=scaleDownUtilizationThreshold,proto3" json:"scaleDownUtilizationThreshold,omitempty"`
	// ScaleDownGpuUtilizationThreshold sets threshold for gpu nodes to be
	// considered for scale down if gpu utilization is over threshold.
	ScaleDownGpuUtilizationThreshold float64 `protobuf:"fixed64,2,opt,name=scaleDownGpuUtilizationThreshold,proto3" json:"scaleDownGpuUtilizationThreshold,omitempty"`
	// ScaleDownUnneededTime sets the duration CA expects a node to be
	// unneeded/eligible for removal before scaling down the node.
	ScaleDownUnneededTime *v1.Duration `protobuf:"bytes,3,opt,name=scaleDownUnneededTime,proto3" json:"scaleDownUnneededTime,omitempty"`
	// ScaleDownUnreadyTime represents how long an unready node should be
	// unneeded before it is eligible for scale down.
	ScaleDownUnreadyTime *v1.Duration `protobuf:"bytes,4,opt,name=scaleDownUnreadyTime,proto3" json:"scaleDownUnreadyTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NodeGroupAutoscalingOptions) Reset()         { *m = NodeGroupAutoscalingOptions{} }
func (m *NodeGroupAutoscalingOptions) String() string { return proto.CompactTextString(m) }
func (*NodeGroupAutoscalingOptions) ProtoMessage()    {}
func (*NodeGroupAutoscalingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{33}
}

func (m *NodeGroupAutoscalingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupAutoscalingOptions.Unmarshal(m, b)
}
func (m *NodeGroupAutoscalingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupAutoscalingOptions.Marshal(b, m, deterministic)
}
func (m *NodeGroupAutoscalingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupAutoscalingOptions.Merge(m, src)
}
func (m *NodeGroupAutoscalingOptions) XXX_Size() int {
	return xxx_messageInfo_NodeGroupAutoscalingOptions.Size(m)
}
func (m *NodeGroupAutoscalingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupAutoscalingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupAutoscalingOptions proto.InternalMessageInfo

func (m *NodeGroupAutoscalingOptions) GetScaleDownUtilizationThreshold() float64 {
	if m != nil {
		return m.ScaleDownUtilizationThreshold
	}
	return 0
}

func (m *NodeGroupAutoscalingOptions) GetScaleDownGpuUtilizationThreshold() float64 {
	if m != nil {
		return m.ScaleDownGpuUtilizationThreshold
	}
	return 0
}

func (m *NodeGroupAutoscalingOptions) GetScaleDownUnneededTime() *v1.Duration {
	if m != nil {
		return m.ScaleDownUnneededTime
	}
	return nil
}

func (m *NodeGroupAutoscalingOptions) GetScaleDownUnreadyTime() *v1.Duration {
	if m != nil {
		return m.ScaleDownUnreadyTime
	}
	return nil
}

type NodeGroupAutoscalingOptionsRequest struct {
	// ID of the node group for the request.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// default node group autoscaling options.
	Defaults             *NodeGroupAutoscalingOptions `protobuf:"bytes,2,opt,name=defaults,proto3" json:"defaults,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *NodeGroupAutoscalingOptionsRequest) Reset()         { *m = NodeGroupAutoscalingOptionsRequest{} }
func (m *NodeGroupAutoscalingOptionsRequest) String() string { return proto.CompactTextString(m) }
func (*NodeGroupAutoscalingOptionsRequest) ProtoMessage()    {}
func (*NodeGroupAutoscalingOptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{34}
}

func (m *NodeGroupAutoscalingOptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupAutoscalingOptionsRequest.Unmarshal(m, b)
}
func (m *NodeGroupAutoscalingOptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupAutoscalingOptionsRequest.Marshal(b, m, deterministic)
}
func (m *NodeGroupAutoscalingOptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupAutoscalingOptionsRequest.Merge(m, src)
}
func (m *NodeGroupAutoscalingOptionsRequest) XXX_Size() int {
	return xxx_messageInfo_NodeGroupAutoscalingOptionsRequest.Size(m)
}
func (m *NodeGroupAutoscalingOptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupAutoscalingOptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupAutoscalingOptionsRequest proto.InternalMessageInfo

func (m *NodeGroupAutoscalingOptionsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeGroupAutoscalingOptionsRequest) GetDefaults() *NodeGroupAutoscalingOptions {
	if m != nil {
		return m.Defaults
	}
	return nil
}

type NodeGroupAutoscalingOptionsResponse struct {
	// autoscaling options for the requested node.
	NodeGroupAutoscalingOptions *NodeGroupAutoscalingOptions `protobuf:"bytes,1,opt,name=nodeGroupAutoscalingOptions,proto3" json:"nodeGroupAutoscalingOptions,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}                     `json:"-"`
	XXX_unrecognized            []byte                       `json:"-"`
	XXX_sizecache               int32                        `json:"-"`
}

func (m *NodeGroupAutoscalingOptionsResponse) Reset()         { *m = NodeGroupAutoscalingOptionsResponse{} }
func (m *NodeGroupAutoscalingOptionsResponse) String() string { return proto.CompactTextString(m) }
func (*NodeGroupAutoscalingOptionsResponse) ProtoMessage()    {}
func (*NodeGroupAutoscalingOptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a2b59a9995d10f3, []int{35}
}

func (m *NodeGroupAutoscalingOptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeGroupAutoscalingOptionsResponse.Unmarshal(m, b)
}
func (m *NodeGroupAutoscalingOptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeGroupAutoscalingOptionsResponse.Marshal(b, m, deterministic)
}
func (m *NodeGroupAutoscalingOptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeGroupAutoscalingOptionsResponse.Merge(m, src)
}
func (m *NodeGroupAutoscalingOptionsResponse) XXX_Size() int {
	return xxx_messageInfo_NodeGroupAutoscalingOptionsResponse.Size(m)
}
func (m *NodeGroupAutoscalingOptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeGroupAutoscalingOptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeGroupAutoscalingOptionsResponse proto.InternalMessageInfo

func (m *NodeGroupAutoscalingOptionsResponse) GetNodeGroupAutoscalingOptions() *NodeGroupAutoscalingOptions {
	if m != nil {
		return m.NodeGroupAutoscalingOptions
	}
	return nil
}

func init() {
	proto.RegisterEnum("clusterautoscaler.cloudprovider.v1.externalgrpc.InstanceStatus_InstanceState", InstanceStatus_InstanceState_name, InstanceStatus_InstanceState_value)
	proto.RegisterType((*NodeGroup)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroup")
	proto.RegisterType((*ExternalGrpcNode)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.ExternalGrpcNode")
	proto.RegisterMapType((map[string]string)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.ExternalGrpcNode.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.ExternalGrpcNode.LabelsEntry")
	proto.RegisterType((*NodeGroupsRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupsRequest")
	proto.RegisterType((*NodeGroupsResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupsResponse")
	proto.RegisterType((*NodeGroupForNodeRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupForNodeRequest")
	proto.RegisterType((*NodeGroupForNodeResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupForNodeResponse")
	proto.RegisterType((*PricingNodePriceRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.PricingNodePriceRequest")
	proto.RegisterType((*PricingNodePriceResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.PricingNodePriceResponse")
	proto.RegisterType((*PricingPodPriceRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.PricingPodPriceRequest")
	proto.RegisterType((*PricingPodPriceResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.PricingPodPriceResponse")
	proto.RegisterType((*GPULabelRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.GPULabelRequest")
	proto.RegisterType((*GPULabelResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.GPULabelResponse")
	proto.RegisterType((*GetAvailableGPUTypesRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.GetAvailableGPUTypesRequest")
	proto.RegisterType((*GetAvailableGPUTypesResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.GetAvailableGPUTypesResponse")
	proto.RegisterMapType((map[string]*any.Any)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.GetAvailableGPUTypesResponse.GpuTypesEntry")
	proto.RegisterType((*CleanupRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.CleanupRequest")
	proto.RegisterType((*CleanupResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.CleanupResponse")
	proto.RegisterType((*RefreshRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.RefreshRequest")
	proto.RegisterType((*RefreshResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.RefreshResponse")
	proto.RegisterType((*NodeGroupTargetSizeRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupTargetSizeRequest")
	proto.RegisterType((*NodeGroupTargetSizeResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupTargetSizeResponse")
	proto.RegisterType((*NodeGroupIncreaseSizeRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupIncreaseSizeRequest")
	proto.RegisterType((*NodeGroupIncreaseSizeResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupIncreaseSizeResponse")
	proto.RegisterType((*NodeGroupDeleteNodesRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupDeleteNodesRequest")
	proto.RegisterType((*NodeGroupDeleteNodesResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupDeleteNodesResponse")
	proto.RegisterType((*NodeGroupDecreaseTargetSizeRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupDecreaseTargetSizeRequest")
	proto.RegisterType((*NodeGroupDecreaseTargetSizeResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupDecreaseTargetSizeResponse")
	proto.RegisterType((*NodeGroupNodesRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupNodesRequest")
	proto.RegisterType((*NodeGroupNodesResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupNodesResponse")
	proto.RegisterType((*Instance)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.Instance")
	proto.RegisterType((*InstanceStatus)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.InstanceStatus")
	proto.RegisterType((*InstanceErrorInfo)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.InstanceErrorInfo")
	proto.RegisterType((*NodeGroupTemplateNodeInfoRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupTemplateNodeInfoRequest")
	proto.RegisterType((*NodeGroupTemplateNodeInfoResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupTemplateNodeInfoResponse")
	proto.RegisterType((*NodeGroupAutoscalingOptions)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupAutoscalingOptions")
	proto.RegisterType((*NodeGroupAutoscalingOptionsRequest)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupAutoscalingOptionsRequest")
	proto.RegisterType((*NodeGroupAutoscalingOptionsResponse)(nil), "clusterautoscaler.cloudprovider.v1.externalgrpc.NodeGroupAutoscalingOptionsResponse")
}

func init() {
	proto.RegisterFile("cloudprovider/externalgrpc/protos/externalgrpc.proto", fileDescriptor_0a2b59a9995d10f3)
}

var fileDescriptor_0a2b59a9995d10f3 = []byte{
	// 1554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x59, 0xcf, 0x6f, 0xdc, 0xc4,
	0x17, 0x8f, 0x77, 0x93, 0x36, 0xfb, 0xf6, 0x9b, 0x64, 0x33, 0xdd, 0xb6, 0x5b, 0xf7, 0xc7, 0x37,
	0x18, 0x21, 0x42, 0x05, 0x5e, 0x1a, 0x22, 0xd4, 0x56, 0x02, 0x9a, 0x66, 0xdb, 0x6d, 0x4a, 0x52,
	0x52, 0x27, 0x51, 0xa0, 0x5c, 0x98, 0xac, 0x27, 0x8e, 0x15, 0x67, 0xec, 0xfa, 0x47, 0xda, 0xed,
	0x89, 0x0b, 0x1c, 0x91, 0x38, 0x71, 0xeb, 0x05, 0x09, 0x89, 0x2b, 0x12, 0x88, 0x1b, 0x12, 0xe2,
	0xd4, 0x2b, 0xff, 0x05, 0xff, 0x01, 0x37, 0xe4, 0xf1, 0xd8, 0x1e, 0xef, 0x7a, 0xd3, 0xae, 0x77,
	0x91, 0x38, 0x65, 0xe7, 0xcd, 0xcc, 0xe7, 0x7d, 0xe6, 0xf9, 0xcd, 0x9b, 0xf7, 0x51, 0x60, 0xb9,
	0x63, 0xd9, 0x81, 0xee, 0xb8, 0xf6, 0xb1, 0xa9, 0x13, 0xb7, 0x49, 0x9e, 0xfa, 0xc4, 0xa5, 0xd8,
	0x32, 0x5c, 0xa7, 0xd3, 0x74, 0x5c, 0xdb, 0xb7, 0xbd, 0x8c, 0x4d, 0x65, 0x36, 0xd4, 0xec, 0x58,
	0x81, 0xe7, 0x13, 0x17, 0x07, 0xbe, 0xed, 0x75, 0xb0, 0x45, 0x5c, 0x35, 0x83, 0xa3, 0x1e, 0x5f,
	0x53, 0xc5, 0x6d, 0xf2, 0x05, 0xc3, 0xb6, 0x0d, 0x8b, 0x44, 0x90, 0x7b, 0xc1, 0x7e, 0x13, 0xd3,
	0x6e, 0x84, 0x25, 0x2f, 0x1f, 0x5e, 0xf7, 0x54, 0xd3, 0x6e, 0x62, 0xc7, 0x3c, 0xc2, 0x9d, 0x03,
	0x93, 0x12, 0xb7, 0xdb, 0x74, 0x0e, 0x8d, 0xd0, 0xe0, 0x35, 0x8f, 0x88, 0x8f, 0x9b, 0xc7, 0xd7,
	0x9a, 0x06, 0xa1, 0xc4, 0xc5, 0x3e, 0xd1, 0xf9, 0x2e, 0x25, 0xdd, 0xd5, 0xec, 0xd8, 0x2e, 0xc9,
	0x59, 0xa3, 0x10, 0xa8, 0x3c, 0xb0, 0x75, 0xd2, 0x76, 0xed, 0xc0, 0x41, 0xb3, 0x50, 0x32, 0xf5,
	0x86, 0xb4, 0x20, 0x2d, 0x56, 0xb4, 0x92, 0xa9, 0xa3, 0x06, 0x9c, 0x3e, 0x32, 0xe9, 0x96, 0xf9,
	0x8c, 0x34, 0x4a, 0x0b, 0xd2, 0xe2, 0x94, 0x16, 0x0f, 0xd9, 0x0c, 0x7e, 0xca, 0x66, 0xca, 0x7c,
	0x26, 0x1a, 0xa2, 0x3a, 0x4c, 0xe9, 0x64, 0x2f, 0x30, 0x1a, 0x93, 0x0c, 0x26, 0x1a, 0x28, 0xcf,
	0xcb, 0x50, 0xbb, 0xc3, 0x0f, 0xdb, 0x76, 0x9d, 0x4e, 0xe8, 0x13, 0x5d, 0x01, 0x88, 0x83, 0xb1,
	0xd6, 0xe2, 0x6e, 0x05, 0x0b, 0x42, 0x30, 0x49, 0xf1, 0x51, 0xe4, 0xbb, 0xa2, 0xb1, 0xdf, 0x88,
	0xc0, 0x29, 0x0b, 0xef, 0x11, 0xcb, 0x6b, 0x94, 0x17, 0xca, 0x8b, 0xd5, 0xa5, 0x0d, 0x75, 0xc8,
	0x30, 0xab, 0xbd, 0x34, 0xd4, 0x75, 0x86, 0x77, 0x87, 0xfa, 0x6e, 0x57, 0xe3, 0xe0, 0xc8, 0x87,
	0x2a, 0xa6, 0xd4, 0xf6, 0xb1, 0x6f, 0xda, 0xd4, 0x6b, 0x4c, 0x32, 0x5f, 0xda, 0xe8, 0xbe, 0x56,
	0x52, 0xd0, 0xc8, 0xa1, 0xe8, 0x46, 0xbe, 0x01, 0x55, 0x81, 0x0c, 0xaa, 0x41, 0xf9, 0x90, 0x74,
	0x79, 0x60, 0xc2, 0x9f, 0x61, 0x70, 0x8f, 0xb1, 0x15, 0xc4, 0x21, 0x89, 0x06, 0x37, 0x4b, 0xd7,
	0x25, 0xf9, 0x43, 0xa8, 0xf5, 0x62, 0x0f, 0xb3, 0x5f, 0x39, 0x03, 0xf3, 0x49, 0x1e, 0x78, 0x1a,
	0x79, 0x1c, 0x10, 0xcf, 0x57, 0x1c, 0x40, 0xa2, 0xd1, 0x73, 0x6c, 0xea, 0x11, 0xf4, 0x08, 0x80,
	0x26, 0xd6, 0x86, 0xc4, 0x42, 0x73, 0x73, 0xe8, 0xd0, 0x24, 0xc0, 0x9a, 0x80, 0xa6, 0x38, 0x70,
	0x3e, 0x99, 0xb8, 0x6b, 0xbb, 0xe1, 0x6f, 0x4e, 0x06, 0xed, 0xc0, 0x64, 0xb8, 0x90, 0x1d, 0xa7,
	0xba, 0xb4, 0x32, 0xf2, 0xb7, 0xd0, 0x18, 0x9c, 0xe2, 0x43, 0xa3, 0xdf, 0x23, 0x3f, 0xe9, 0xa7,
	0x50, 0x49, 0xb8, 0x71, 0xbf, 0xa3, 0x1c, 0x34, 0x05, 0x53, 0xbe, 0x2c, 0xc1, 0xf9, 0x4d, 0xd7,
	0xec, 0x98, 0xd4, 0x08, 0xe7, 0xc3, 0x9f, 0xff, 0xf2, 0x41, 0xd1, 0x3d, 0xa8, 0x78, 0x3e, 0x76,
	0xfd, 0x6d, 0x93, 0x5f, 0xa9, 0xea, 0xd2, 0x55, 0x35, 0xaa, 0x10, 0xaa, 0x58, 0x57, 0x54, 0xe7,
	0xd0, 0x08, 0x0d, 0x9e, 0x1a, 0xd6, 0x95, 0x10, 0x3d, 0xdc, 0xa1, 0xa5, 0x9b, 0x51, 0x0b, 0x4e,
	0x13, 0xaa, 0x33, 0x9c, 0xf2, 0xd0, 0x38, 0xf1, 0x56, 0xe5, 0x5d, 0x68, 0xf4, 0x47, 0x80, 0x07,
	0xbe, 0x0e, 0x53, 0x4e, 0x68, 0x60, 0x31, 0x90, 0xb4, 0x68, 0xa0, 0xfc, 0x29, 0xc1, 0x39, 0xbe,
	0x65, 0xd3, 0xd6, 0x33, 0x31, 0x7b, 0x0b, 0xca, 0x8e, 0xad, 0xf3, 0x90, 0x9d, 0x17, 0xe8, 0xa8,
	0x61, 0xe1, 0x0b, 0x9d, 0x6f, 0xda, 0xba, 0x16, 0xae, 0xf9, 0xcf, 0xc5, 0xa1, 0x99, 0x64, 0x42,
	0x7a, 0xa8, 0x13, 0xc3, 0x30, 0x0f, 0x73, 0xed, 0xcd, 0x1d, 0x56, 0x28, 0xe2, 0x8b, 0xba, 0x08,
	0xb5, 0xd4, 0x94, 0x6e, 0x66, 0xc5, 0x8c, 0xdf, 0xff, 0x68, 0xa0, 0x5c, 0x86, 0x8b, 0x6d, 0xe2,
	0xaf, 0x1c, 0x63, 0xd3, 0xc2, 0x7b, 0x16, 0x69, 0x6f, 0xee, 0x6c, 0x77, 0x1d, 0x92, 0xdc, 0xf8,
	0xbf, 0x24, 0xb8, 0x94, 0x3f, 0xcf, 0x51, 0x9f, 0xc0, 0xb4, 0xe1, 0x04, 0xcc, 0xc6, 0xaf, 0xfe,
	0xe7, 0x43, 0x27, 0xe8, 0x49, 0x0e, 0xd4, 0x36, 0x47, 0x8f, 0xca, 0x63, 0xe2, 0x4c, 0x7e, 0x08,
	0x33, 0x99, 0xa9, 0x9c, 0xea, 0x76, 0x55, 0xac, 0x6e, 0xd5, 0xa5, 0xba, 0x1a, 0x3d, 0xa8, 0x6a,
	0xfc, 0xa0, 0xaa, 0x2b, 0xb4, 0x2b, 0xd6, 0xbc, 0x1a, 0xcc, 0xae, 0x5a, 0x04, 0xd3, 0xc0, 0x89,
	0x8f, 0x3f, 0x0f, 0x73, 0x89, 0x25, 0xe2, 0x13, 0x2e, 0xd2, 0xc8, 0xbe, 0x4b, 0xbc, 0x03, 0x61,
	0x51, 0x62, 0xe1, 0x8b, 0xde, 0x06, 0x39, 0xb9, 0xe6, 0xdb, 0xd8, 0x35, 0x88, 0x1f, 0xbe, 0x85,
	0x71, 0x72, 0xf6, 0x3c, 0xab, 0xca, 0x07, 0x70, 0x31, 0x77, 0x35, 0x0f, 0xf1, 0x15, 0x00, 0x3f,
	0xb1, 0xb2, 0x6d, 0x53, 0x9a, 0x60, 0x51, 0x5a, 0x70, 0x29, 0xd9, 0xbe, 0x46, 0x3b, 0x2e, 0xc1,
	0x1e, 0x11, 0xdd, 0xb1, 0x17, 0xd8, 0xf2, 0x31, 0xdf, 0x1a, 0x0d, 0x38, 0x89, 0x52, 0x42, 0xe2,
	0xff, 0x70, 0x79, 0x00, 0x0a, 0x3f, 0xd3, 0xd7, 0x92, 0x40, 0xb3, 0x45, 0x2c, 0xe2, 0x93, 0x70,
	0x18, 0xa7, 0x0a, 0xda, 0x85, 0xa9, 0xb0, 0xae, 0xc4, 0x69, 0x30, 0x86, 0x3a, 0x15, 0xe1, 0xf5,
	0x31, 0xbd, 0x22, 0x9c, 0x37, 0xc3, 0x83, 0x13, 0xbd, 0x0f, 0x8a, 0x30, 0x1f, 0x9d, 0xa4, 0xff,
	0x23, 0xbc, 0x5a, 0x54, 0xde, 0x80, 0xd7, 0x4f, 0xc4, 0xe2, 0x2e, 0xdf, 0x84, 0xb3, 0xc9, 0xb2,
	0x4c, 0x50, 0x7a, 0x3f, 0xf5, 0x63, 0x38, 0xd7, 0xbb, 0x90, 0x7f, 0xe5, 0x5d, 0xa8, 0x98, 0xd4,
	0xf3, 0x31, 0xed, 0x24, 0x21, 0xbc, 0x31, 0x74, 0x08, 0xd7, 0x38, 0x82, 0x96, 0x62, 0x29, 0x1e,
	0x4c, 0xc7, 0xe6, 0xbe, 0x86, 0x6e, 0x17, 0x4e, 0x79, 0x3e, 0xf6, 0x03, 0x8f, 0x5f, 0x91, 0x8f,
	0x0a, 0x7b, 0xdc, 0x62, 0x30, 0x1a, 0x87, 0x53, 0x5e, 0x94, 0x60, 0x36, 0x3b, 0x85, 0x3c, 0x98,
	0x31, 0x05, 0x4b, 0x94, 0xc9, 0xb3, 0x05, 0x1a, 0xb6, 0x2c, 0x6e, 0x66, 0x48, 0xb4, 0xac, 0x0f,
	0xf4, 0x05, 0x54, 0x88, 0xeb, 0xda, 0xee, 0x1a, 0xdd, 0xb7, 0xf9, 0x19, 0x6f, 0x17, 0x76, 0x78,
	0x27, 0x46, 0xd2, 0x52, 0x50, 0x05, 0xc3, 0x4c, 0x86, 0x01, 0x9a, 0x83, 0x6a, 0x40, 0x3d, 0x87,
	0x74, 0xcc, 0x7d, 0x93, 0xe8, 0xb5, 0x09, 0x74, 0x06, 0xe6, 0x62, 0x52, 0x5a, 0x40, 0xa9, 0x49,
	0x8d, 0x9a, 0x84, 0xea, 0x50, 0x8b, 0x8d, 0xab, 0x2e, 0xc1, 0x7e, 0x68, 0x2d, 0x89, 0x56, 0x96,
	0xd9, 0xa1, 0xb5, 0xac, 0x7c, 0x25, 0xc1, 0x7c, 0x1f, 0x07, 0x74, 0x89, 0x1f, 0x6d, 0x35, 0xee,
	0x0d, 0x2a, 0x5a, 0x6a, 0x40, 0x0a, 0xfc, 0x8f, 0x0d, 0x36, 0x88, 0xe7, 0x61, 0x23, 0x6e, 0xf0,
	0x32, 0x36, 0xa4, 0x02, 0x32, 0x45, 0xd8, 0x55, 0x0b, 0x7b, 0x1e, 0xef, 0xdf, 0x73, 0x66, 0x94,
	0x25, 0x58, 0x48, 0xeb, 0x14, 0x39, 0x72, 0x2c, 0x1c, 0x5d, 0x3d, 0x16, 0x92, 0x01, 0x09, 0xff,
	0x19, 0xbc, 0x76, 0xc2, 0x1e, 0x9e, 0xfb, 0xcb, 0x30, 0x4d, 0xb9, 0x8d, 0x3f, 0xd9, 0x8d, 0xbc,
	0x27, 0x9b, 0x15, 0x85, 0x64, 0xa5, 0xf2, 0x77, 0x49, 0x28, 0x48, 0x2b, 0xfc, 0x63, 0x9a, 0xd4,
	0xf8, 0xc4, 0x61, 0x3d, 0x2f, 0x6a, 0xc1, 0x65, 0xf6, 0x79, 0x5b, 0xf6, 0x13, 0xba, 0xe3, 0x9b,
	0x96, 0xf9, 0x8c, 0x35, 0xc3, 0xdb, 0x07, 0x61, 0xa9, 0xb6, 0x2d, 0x9d, 0xbf, 0xa2, 0x27, 0x2f,
	0x42, 0xf7, 0x61, 0x21, 0x59, 0xd0, 0x76, 0x82, 0x5c, 0xa0, 0x12, 0x03, 0x7a, 0xe9, 0x3a, 0xa4,
	0xc3, 0xd9, 0xd4, 0x19, 0xa5, 0x84, 0xe8, 0x44, 0x6c, 0x17, 0xd4, 0x57, 0x6b, 0x17, 0x5a, 0x81,
	0xcb, 0x70, 0xb5, 0x7c, 0x30, 0xb4, 0x07, 0x75, 0x61, 0xc2, 0x25, 0x58, 0xef, 0x32, 0x27, 0x93,
	0x85, 0x9c, 0xe4, 0x62, 0x29, 0xcf, 0x25, 0xa1, 0xc8, 0xf6, 0xc7, 0x7e, 0x40, 0x36, 0xa0, 0x03,
	0x98, 0xd6, 0xc9, 0x3e, 0x0e, 0x2c, 0x3f, 0xae, 0x38, 0xeb, 0xc5, 0xfb, 0xe7, 0x1c, 0xb7, 0x09,
	0xba, 0xf2, 0x8b, 0x24, 0x54, 0xee, 0x3c, 0x82, 0x3c, 0xf5, 0xbe, 0x91, 0xe0, 0x22, 0x1d, 0xbc,
	0x8e, 0xa7, 0xe3, 0x78, 0x59, 0x9e, 0xe4, 0x70, 0xe9, 0xb7, 0x3a, 0xcc, 0xac, 0x86, 0xd0, 0x9b,
	0x1c, 0x1a, 0x7d, 0x27, 0x01, 0xa4, 0xb2, 0x0b, 0xdd, 0x2e, 0xce, 0x25, 0xfe, 0x2e, 0xf2, 0xea,
	0x48, 0x18, 0xfc, 0xd1, 0x9b, 0x40, 0x3f, 0x4a, 0x50, 0xeb, 0x15, 0x4b, 0xe8, 0x5e, 0x71, 0xec,
	0xac, 0xc2, 0x93, 0xd7, 0xc6, 0x80, 0x94, 0xe1, 0xda, 0xab, 0x2f, 0x0a, 0x70, 0x1d, 0x20, 0xd2,
	0x0a, 0x70, 0x1d, 0x24, 0x76, 0x94, 0x09, 0xf4, 0x83, 0x04, 0x73, 0x3d, 0x1a, 0x00, 0xb5, 0x8b,
	0x3a, 0xe8, 0x91, 0x46, 0xf2, 0xbd, 0xd1, 0x81, 0x12, 0xa2, 0xdf, 0x4a, 0x30, 0x1d, 0x0b, 0x0d,
	0x74, 0x6b, 0xf8, 0xc6, 0x3f, 0x2b, 0x5b, 0xe4, 0x95, 0x11, 0x10, 0x12, 0x4e, 0x3f, 0x4b, 0x50,
	0xcf, 0x53, 0x14, 0x68, 0x7d, 0x4c, 0xc2, 0x24, 0xe2, 0xba, 0x31, 0x56, 0x99, 0xa3, 0x4c, 0x84,
	0x95, 0xe8, 0x34, 0x17, 0x1b, 0x68, 0xf8, 0x3e, 0x2c, 0x2b, 0x5c, 0xe4, 0x5b, 0xc5, 0x01, 0x32,
	0x84, 0xb8, 0xb0, 0x29, 0x40, 0x28, 0x2b, 0x92, 0x0a, 0x10, 0xea, 0xd5, 0x54, 0x13, 0xe8, 0x27,
	0x09, 0xce, 0xe4, 0x08, 0x25, 0xf4, 0x71, 0xf1, 0x3a, 0xd1, 0xa7, 0x0b, 0xe4, 0xf5, 0xf1, 0x80,
	0x25, 0xa4, 0x7f, 0x95, 0x04, 0x6d, 0x20, 0x0a, 0x2b, 0xb4, 0x51, 0xdc, 0x53, 0x8e, 0xcc, 0x93,
	0x1f, 0x8c, 0x0b, 0x2e, 0x73, 0x93, 0xf2, 0x94, 0x16, 0x1a, 0x21, 0x46, 0xfd, 0xc2, 0x51, 0xde,
	0x18, 0x13, 0x5a, 0xc2, 0xfb, 0x45, 0x56, 0xa9, 0xf6, 0xaa, 0x36, 0xb4, 0x35, 0x8a, 0xc3, 0x01,
	0x7a, 0x52, 0xde, 0x1e, 0x2f, 0x68, 0x72, 0x98, 0xef, 0x25, 0x98, 0xcd, 0x4a, 0x46, 0x74, 0xb7,
	0xb8, 0xab, 0x4c, 0xe0, 0xdb, 0x23, 0xe3, 0x24, 0x2c, 0xff, 0x90, 0xe0, 0xc2, 0xc0, 0x3e, 0x1f,
	0x3d, 0x1c, 0xe1, 0x4e, 0xe5, 0xeb, 0x0c, 0x59, 0x1b, 0x27, 0x64, 0x72, 0x8c, 0xdf, 0xc5, 0x0a,
	0xd3, 0x26, 0x7e, 0x2c, 0x25, 0xb6, 0xc6, 0xda, 0xff, 0x8d, 0x9e, 0x31, 0x83, 0x1b, 0x5a, 0x65,
	0xe2, 0xf6, 0xfb, 0x8f, 0x96, 0x39, 0xf0, 0x3b, 0x29, 0x72, 0xf3, 0xa5, 0xff, 0xb3, 0xda, 0x3b,
	0xc5, 0xfe, 0xbe, 0xf7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0x21, 0x8d, 0xe5, 0xdf, 0x1a,
	0x00, 0x00,
}
