{
 "title": "Cluster autoscaling details",
 "tags": [ "autoscaling" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Current node groups",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(nodegroup) (last_over_time(rs_infra_scaler_nodes_in_nodegroup[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Playbook runs",
   "type": "logs",
   "description": "Logs corresponding of a playbook run.",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"kube-system\", container=\"rs-infra-scaler\"} |= `Running` | pattern `<_> Running <log>` | line_format `Running {{ .log }}`"
    }
   ]
  },
  {
   "title": "Last scaling operations",
   "type": "logs",
   "gridPos": { "h": 12, "w": 7, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"cluster-autoscaler\"} |~ `(Scale-down:)|(Final scale-up plan:)` | regexp `.*\\.go:[1-9]{1,3}](?P<plan>.*)` | line_format `{{ .plan }}`"
    }
   ]
  },
  {
   "title": "Node groups evolution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(nodegroup) (rs_infra_scaler_nodes_in_nodegroup)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}